#define COOP_DEFAULT_HUBBLE 0.7d0
#define COOP_DEFAULT_TCMB   2.726d0
#define COOP_DEFAULT_NUM_NEUTRINO_SPECIES  3.d0
#define COOP_DEFAULT_YHE  0.25d0
#define COOP_DEFAULT_K_PIVOT = 0.05d0


#define COOP_DEFAULT_OMEGA_C = 0.255d0
#define COOP_DEFAULT_OMEGA_B = 0.045d0
#define COOP_DEFAULT_TAU_RE = 0.09d0
#define COOP_DEFAULT_SIGMA8 = 0.8d0
#define COOP_DEFAULT_NS = 0.96d0
#define COOP_DEFAULT_NRUN = 0.d0
#define COOP_DEFAULT_AS = 2.2d-9

#define COOP_DEFAULT_DE_W0 = -1.d0
#define COOP_DEFAULT_DE_WA = 0.d0
#define COOP_DEFAULT_DE_EPSILON_S = 0.d0
#define COOP_DEFAULT_DE_EPSILON_INF = 0.d0
#define COOP_DEFAULT_DE_ZETA_S = 0.d0
#define COOP_DEFAULT_DE_Q = 0.d0
